# Generated by Django 4.0.5 on 2022-06-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.CharField(default='', max_length=500)),
                ('product_dimensions', models.CharField(default='', max_length=200)),
                ('weight', models.CharField(default='', max_length=50)),
                ('asin', models.CharField(default='', max_length=10)),
                ('price', models.FloatField()),
                ('rank', models.IntegerField()),
                ('cat', models.CharField(default='', max_length=100)),
                ('review_counts', models.IntegerField()),
                ('ratings', models.FloatField(default='5.0')),
                ('date_first_available', models.DateField(default='1990-01-01')),
            ],
        ),
    ]
