# Generated by Django 4.0.5 on 2022-07-04 14:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rank',
        ),
        migrations.AddField(
            model_name='product',
            name='add_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='采集时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='ASIN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.CharField(default='', max_length=100, verbose_name='类目'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_first_available',
            field=models.DateField(default='1990-01-01', verbose_name='上架日期'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_dimensions',
            field=models.CharField(default='', max_length=200, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.FloatField(default='5.0', verbose_name='评分'),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_counts',
            field=models.IntegerField(verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.CharField(default='', max_length=50, verbose_name='重量'),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('add_time', models.DateField(auto_now_add=True, verbose_name='采集时间')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
