# Generated by Django 4.0.5 on 2022-07-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_rank_product_add_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='product_id',
            new_name='product',
        ),
    ]
