# Generated by Django 3.2.13 on 2022-07-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seller',
            name='product_sel_sell_id_98fac8_idx',
        ),
        migrations.RenameField(
            model_name='seller',
            old_name='sell_id',
            new_name='seller_id',
        ),
        migrations.AddIndex(
            model_name='seller',
            index=models.Index(fields=['seller_id'], name='product_sel_seller__edda54_idx'),
        ),
    ]
