# Generated by Django 3.2.13 on 2022-07-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220706_1610'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='product_rev_product_98782c_idx',
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='product_rev_product_b4e72e_idx'),
        ),
    ]
