# Generated by Django 4.0.5 on 2022-07-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_seller_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='business_addr',
            field=models.CharField(default='', max_length=300, verbose_name='公司地址'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='business_name',
            field=models.CharField(default='', max_length=300, verbose_name='公司名称'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='days_30_ratings',
            field=models.IntegerField(default=0, verbose_name='30天fd数'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='days_90_ratings',
            field=models.IntegerField(default=0, verbose_name='90天fd数'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='life_ratings',
            field=models.IntegerField(default=0, verbose_name='总fd数'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='year_ratings',
            field=models.IntegerField(default=0, verbose_name='一年fd数'),
        ),
    ]
