# Generated by Django 4.0.5 on 2022-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_seller_business_addr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
        migrations.AddField(
            model_name='seller',
            name='display',
            field=models.BooleanField(default=True, verbose_name='是否展示'),
        ),
        migrations.AddField(
            model_name='seller',
            name='product_counts',
            field=models.IntegerField(default=0, verbose_name='产品数'),
        ),
    ]
